# game setup

ENABLED		= True
DISABLED	= False

NAME		= 'Chess'
WIDTH		= 450
HEIGHT		= 700
MENU_WIDTH	= 182
MENU_HEIGHT= 300
MENU_COLOR = 'Dark Grey'
MENU_BUTTON= 'Yellow'
OFFSET		= 3
FPS			= 10
TILESIZE	= 44
FONT		= 'Arial'
FONT_COLOR	= 'White'
FONT_SIZE	= 12
WHITE_TILE	= 'dark khaki'
BLACK_TILE	= 'dark red'
SELECTED	= 'salmon'
HINT		= 'plum'
COOLDOWN	= 450

SETTINGS	= ENABLED
WHITEFIRST	= ENABLED
CAPTURES	= ENABLED
CAPTURED_W	= (60, 60, 60)
CAPTURED_B	= (180, 180, 180)
SCORE		= ENABLED
DEVMODE 	= DISABLED

